### ISSUE TITLE
Is it possible to recover the device that performed the activity?

### ISSUE THREAD

**Issue by ravenfeld** [yangyang5214/merge-fit#1]
My equipment is not recovered and I think that's a shame. Is it possible to correct this by recovering the information in the 1st file to avoid putting development in manufacturer and other information in device info?

**Comment by yangyang5214** [comment]
Okay, I will support it.

**Comment by ravenfeld** [comment]
Thank you very much, I was using fit File Tools but garmin won't import their file whereas yours does but it lacks information which is a shame and I like the fact that it runs on my machine so I don't have to worry about weight.

**Comment by ravenfeld** [comment]
```
        short manufacturerId = Manufacturer.DEVELOPMENT;
        short productId = 1;
        float softwareVersion = 1;
```
I've just seen that in the code it's indicated in hardcopy, that's why.

**Comment by ravenfeld** [comment]
I don't know how to compile this project, I'm doing Android, but I'll try to look at it this evening.

**Comment by yangyang5214** [comment]
https://github.com/yangyang5214/merge-fit/pull/2

I updated the readme.md

**Comment by yangyang5214** [comment]
Done. 

https://github.com/yangyang5214/merge-fit/releases/tag/v0.1.5
